### ISSUE TITLE
Convert both directions between 'simple' antenna positions and ITRF positions

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/pyuvdata#115]

**Comment by bhazelton** [comment]
It is possible that I have effectively addressed this in my pull request #155. I think that ENU (east, north, up) may well be what we meant by 'simple' antenna positions. I don't really remember the context for this issue, though, so I'm not sure. Can you comment @mkolopanis @aelanman?

**Comment by aelanman** [comment]
I remember being interested in this issue because I wanted to use pyuvdata to pull antenna positions and make cal files, which store antenna positions in ENU coordinates relative to the array center. I think that's what we meant by 'simple.' I made some progress in rotating the ITRF to ENU coordinates, but consistently found the array shifted and rotated a little from where it should be (comparing mwa antenna positions from a cotter-generated uvfits file to a table on the mwa wiki). There are some lines in cotter which I suspect were storing the ITRF table incorrectly. If so, it wouldn't be noticeable because nothing else uses the ITRF antenna positions. From there, I decided instead to get antenna positions from the unphased uvw array, to more success.

It looks like pull request #155 _does_ address this issue. I'm curious if you'll see the same shift/rotation that I saw when trying to rotate the ITRF positions to ENU.

**Comment by bhazelton** [comment]
That's interesting, I didn't realize that was the blocking problem for you. Do you still have the code to make those comparisons?

**Comment by aelanman** [comment]
I can't find my original code for ITRF conversion... I may have deleted it. I was doing the conversion with a pair of rotation matrices, which I think were pretty close to what you have in your pull request. I'll write up something new to make the comparison.

**Comment by bhazelton** [comment]
@aelanman Is this issue resolved?

**Comment by aelanman** [comment]
The utility functions you added for rotating coordinates should be enough to consider this issue resolved.
