### ISSUE TITLE
Remove dependency on pyfits

### ISSUE THREAD

**Issue by astrofrog** [HERA-Team/pyuvdata#116]
PyFITS is now included in Astropy (as ``astropy.io.fits``) so the depdency on pyfits can be removed and the imports should be updated to reflect this.

An easy way to update the imports is to do:

```python
import pyfits
```

by

```python
from astropy.io import fits as pyfits
```

**Comment by bhazelton** [comment]
The pyfits dependency is caused by the aipy dependency (which we'd like to remove -- see issue #27), in pyuvdata we use astropy.io.fits for all fits manipulation.

It looks like installing aipy using pip installs pyfits, so it doesn't need to be listed as a dependency in pyuvdata. I will remove it from the documentation.
