### ISSUE TITLE
Set up Travis and AppVeyor for continuous integration

### ISSUE THREAD

**Issue by astrofrog** [HERA-Team/pyuvdata#121]
I would strongly encourage you to set up Travis and AppVeyor to run the test suite whenever you make a change or pull request, and which will also better test that all the file I/O works correctly in Windows, Linux, and MacOS X.

**Comment by bhazelton** [comment]
Travis is working.

After a lot of work on appveyor, I have determined that we are limited by one of our dependencies, aipy, which has c code that does not compile properly on Windows. Since very few people in this field use Windows and since we are planning to remove the aipy dependency long term, I don't think it make sense to sink more time into trying to get it to compile on Windows. I will revisit the appveyor integration after we remove the aipy dependency.
