### ISSUE TITLE
use dict.get instead of dict.pop

### ISSUE THREAD

**Issue by AaronParsons** [HERA-Team/pyuvdata#139]
pyuvdata appears to do the following several times in the code:
hdr = header.copy()
key = hdr.pop('KEY', None)

Presumably, the "copy" is done because dict.pop is destructive to the dictionary.  hdr.get('KEY', None) does the same thing (including the failsafe to None), but is not distructive to the idctionary, and thus does not require a copy.  

I suggest switching to "get" for stylistic reasons.

**Comment by bhazelton** [comment]
The reason we use copy + pop, at least in uvfits.py, is that we need to be able to identify any extra keywords that we haven't already accounted for so that we can preserved them in any files we write out (these keywords are collected in the extra_keywords dict). It's fairly common in uvfits for there to be telescope or processing specific extra keywords that can carry important information that we don't want to lose.
