### ISSUE TITLE
read/write miriad functions do not correctly interpret the integration times

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/pyuvdata#284]
The Miriad standard is for the integration times to mark the *beginning* of the integration (https://github.com/pkgw/viskit/blob/master/doc/uvvars.txt#L367) while the pyuvdata standard is for the times to mark the *center* of the observation.

The times read from & written to Miriad files need to be corrected by half the integration time so that the pyuvdata time_array values correspond to the middle of the integration. Tests to detect this error need to be added.

**Comment by nkern** [comment]
I've got a start on the branch `uvdata_time_array_fix`. I'm running into an issue where not only does the `time_array` and `lst_array` need to be shifted by half an integration, but also the `zenith_ra` array needs to be updated (and presumably the `uvw_array` too?). This is a little complicated because right now, in `miriad.py` the zenith_ra information is directly propagated from the Miriad file, instead of re-calculated based on `time_array` and `telescope_location`, causing one of the tests to fail. @bhazelton I don't want to do too much re-organizing of how `miriad.py` works, so let me know if there is a particular way in which you want to handle this.

**Comment by bhazelton** [comment]
oh, dear. I should really stop predicting that things are easy. I'll take a look and think about it a bit.

**Comment by bhazelton** [comment]
Ok, I've made some progress on your branch, so now only one test fails on the `zenith_ra` thing, which I'm chasing down now. The problem was that in `write_miriad` you were changing the values on the object rather than just changing the values written to the file. I also moved the lst calculation to the utility module because we're now using it not just to set times on the object.

**Comment by bhazelton** [comment]
Ok, Adam helped me figure out the residual issues with `zenith_ra`. I also rebased the branch on master after the scipy/idl fix was merged so that it can pass the Travis checks.
