### ISSUE TITLE
Problem saving modifications to flag array for some uvfits files

### ISSUE THREAD

**Issue by mwilensky768** [HERA-Team/pyuvdata#307]
I have been working with a particular uvfits file, and I am manually flagging and unflagging certain data by assigning slices of the flag array to 1 or 0 as the case requires. I have verified that the method of assignment does indeed change the flag array in the manner expected, but when I write out the uvfits file and read it back in later, some of the flag modifications are not retained. In particular, the slice of the flag array set to 0 does not remain set to 0, but the slice of the flag array set to 1 does remain set to 1. This behavior is not exhibited with test data.

**Comment by adampbeardsley** [comment]
This is a curious bug.
Just to check, can you make sure that the `baseline_array`s of the original UVData object and the re-read one are the same? I could imagine a weird situation where pyuvdata could reorder your data without telling you.
Can you copy the data over somewhere that I can try to recreate this? On enterprise?

**Comment by mwilensky768** [comment]
I have performed the requested check. It seems the baseline arrays are just fine. Using `nt.assert_equal(uv1, uv2)` returns "flag_array parameter value is array, values are not close"

Can you point me to a good directory on enterprise to leave the data?

**Comment by adampbeardsley** [comment]
You can put it anywhere in your `/data4/mwilensky/` directory, just let me know where to find it.

**Comment by adampbeardsley** [comment]
I think the root of the problem is that flag array and nsample_array get tied together in write_uvfits (line 388). For some reason, Mike's data had places where nsample_array = 0, but he was unflagging that data. Looking at his test script:
```
from pyuvdata import UVData
import numpy as np

UV = UVData()
UV.read_uvfits('/data4/mwilensky/uvfits/1061313128_t18_t24_no_flag_mod.uvfits')

# Unflag some middle frequencies and flag all other frequencies
UV.flag_array[:, :, 176:256, :] = 0
UV.nsample_array[:, :, 176:256, :] = 1  # *** I added this line ***
UV.flag_array[:, :, :176, :] = 1
UV.flag_array[:, :, 256:, :] = 1

# Check that this assignment worked
assert(not np.any(UV.flag_array[:, :, 176:256, :]))
assert(np.all(UV.flag_array[:, :, :176, :]) and np.all(UV.flag_array[:, :, 256:, :]))

UV.write_uvfits('/data4/mwilensky/uvfits/1061313128_t18_t24_flag_mod_write_test.uvfits')
UV2 = UVData()
UV2.read_uvfits('/data4/mwilensky/uvfits/1061313128_t18_t24_flag_mod_write_test.uvfits')

# Perform same check as above to see if flag array saved
assert(not np.any(UV2.flag_array[:, :, 176:256, :]))
assert(np.all(UV2.flag_array[:, :, :176, :]) and np.all(UV2.flag_array[:, :, 256:, :]))
```
The script above would fail, until I added the line `UV.nsample_array[:, :, 176:256, :] = 1`. By forcing the nsample_array to be >0 when you try to turn off flags, it now passes.

So I'm not sure whether this is a bug in pyuvdata, or a problem with how the user is using the data. Do we want to ensure nsample_array > 0 for unflagged data, or allow for cases when nsample_array = 0? @bhazelton what do you think?

**Comment by bhazelton** [comment]
Oh, that's very subtle and interesting. Thanks for hunting it @adampbeardsley!

I think that because of the way that uvfits encodes weights and flags, we can't really support unflagging data in uvfits files that have zero weights (or nsamples). So I think we need to add a warning if there are places with zero nsamples that are unflagged. Then the user can decide if they want to explicitly change the nsamples or just let those areas stay flagged.

**Comment by bhazelton** [comment]
I think this has been understood and handled in PR #313
