### ISSUE TITLE
MemoryError in write_uvfits 

### ISSUE THREAD

**Issue by wenyang-li** [HERA-Team/pyuvdata#336]
pyuvdata/pyuvdata/uvfits.py, line 621:
wh_nsample0 = np.where(self.nsample_array == 0)[0]
line 622 (np.any(~self.flag_array[wh_nsample0])) throws an MemoryError.
If change line 621 to be: 
wh_nsample0 = np.where(self.nsample_array == 0)
then it will be fine. Not sure if it is a numpy version problem.

**Comment by bhazelton** [comment]
Ben McKinley also had a memory error with this line (also discussed in issue #328), although we didn't identify that leaving out the `[0]` solved the problem. I believe that the `[0]` was trying to pick the array out of the returned tuple, I worry that not doing that will cause the next line to fail, but if it works it would be a great solution.

Can you test that if you set a particular unflagged visibility's nsample to 0 that line 622 works as expected? If it does, please make this change into a PR!

**Comment by wenyang-li** [comment]
For example, the nsample array has a shape of (448056,1,384,4), thus 6.9e8 elements. If 20% of them are flagged, i.e., 1.4e8 elements found by np.where, np.where should return a tuple with four arrays, with each array having a size of 1.4e8. If wh_nsample0 = np.where(self.nsample_array == 0), self.flag_array[wh_nsample0] is a flattened array with 1.4e8 elements; if wh_nsample0 = np.where(self.nsample_array == 0)[0], then self.flag_array[wh_nsample0] is an array with shape (1.4e8, 1,384,4), thus 2.1e11 elements. I would not be surprised we get this error.

**Comment by bhazelton** [comment]
I think you're right, @wenyang-li, I wrote this check and I didn't test it carefully enough (I keep getting confused by how numpy where and indexing works because of my IDL background). I can work on fixing this, but if you think you know how to do it slickly, feel free to make a PR.

It's trying to do something really simple: check to see if there are any unflagged visibilities with nsample=0. It certainly should not be written so that it requires a lot of memory.

**Comment by bhazelton** [comment]
Ok, I sat down with this and I think you're right, we just need to drop the `[0]` at the end of line 621. I'll make a PR to fix this.
