### ISSUE TITLE
Channel/time selection with read_data=False in read_uvfits()

### ISSUE THREAD

**Issue by aelanman** [HERA-Team/pyuvdata#366]
It seems that when `read_data=False`, time and channel selections are ignored.

**Comment by bhazelton** [comment]
This is by design. A selection is only applied when data are read in, this protects from making changes to the metadata and then reading the data in with different (or no) selections and having the data and metadata mis-match on the object.

I can see this being a little confusing, I suppose it could raise an error if you set selection keywords with read_data=False. Would that help?

**Comment by bhazelton** [comment]
@aelanman This is clarified in the doc string. Do you want a warning as well?

**Comment by aelanman** [comment]
That's fine. I'm actually having trouble remembering where this came up for me... The selection is applied to the metadata after the full data array is read in?

In any case, the design as you described makes sense to me.
