### ISSUE TITLE
Select function

### ISSUE THREAD

**Issue by jpober** [HERA-Team/pyuvdata#38]
Method of the object to downselect times/pols/freqs etc.

**Comment by bhazelton** [comment]
I'm working on this on the select branch. I now have methods on UVData to select specific blts, antennas, times, frequencies or polarizations and to update all the appropriate parameters. I also have some tests, although those should probably be expanded. Do we want a method that can take selections on more than one of these axes and then call the appropriate axis-specific method?

**Comment by jpober** [comment]
I think that's a good idea, a uv.select() which calls e.g. select_antennas().  Would the syntax work to have select() able to call multiple axis-specific selectors simultaneously?

**Comment by bhazelton** [comment]
I think right now I'd have it call them sequentially but that would be
hidden from the user, so if you passed restrictions on several axes it'd do
all of them before returning. If that sounds good I'll just need to think a
little bit about what to call the various keywords for the different axes
so that it'll be clear.

**Comment by bhazelton** [comment]
Implemented.
