### ISSUE TITLE
concatenation blows up memory and perhaps takes forever

### ISSUE THREAD

**Issue by dannyjacobs** [HERA-Team/pyuvdata#383]
Concatenating 4 pol files together got an out of memory error on enteprise (128). Paul confirms that polarization does take a lot of memory.  

James reports it took ~46 minutes to concat a night of data along the time axis. Used 46G of ram and the time did not increase as each file is added.  Danny reports time to concat files _increasing_ with the number of files added.   

Need some concatenation profiling for at least polarization and time.

**Comment by bhazelton** [comment]
Is this really required for the next version (that we're targeting for next week)? And if so, who's going to do it?

**Comment by jaguirre** [comment]
I didn't separately time how long the read of each new file took.  But the combined time for read + concatenate increased linearly with the number of files.  I think that's consistent with the checking that's done for overlap, etc.

At least along the time axis, I'm not sure this is a problem: if you build the big file once, you can access it again fairly quickly (and it doesn't take more space on disk than the original data).  The polarization is weird, though.

**Comment by nkern** [comment]
I have a branch that addresses the super-linear complexity in concatenating many `UVData` objects. When concatenating, say, 5 files, it builds one big UVData objects and inserts data from all 5 into it at once--rather than do ((((1+2)+3)+4)+5)--which is a lot of duplicated computations.

However, I found that, as James said, this doesn't actually speed up the _read-in_ of multiple data files, b/c the total time is bottlenecked by IO rather than data concatenation, so I never submitted the PR, but I can push the branch up if people are interested in looking at it anyways..

**Comment by nkern** [comment]
Its the `combine_uvdata_func` branch, and the function is `uvdata.combine_uvdata`

**Comment by nkern** [comment]
I did profile it, though, and in just the data concatenation step, I get typically an order of magnitude speed-up with this function over the default `1 + 2 + 3 + 4...` behavior (depending on object size etc.)

**Comment by bhazelton** [comment]
Could this be related to what was seen in issue #227?

**Comment by bhazelton** [comment]
@dannyjacobs what progress to we need on this for the next milestone?

**Comment by dannyjacobs** [comment]
This is a factor 3.7 bloat but doesn't require >128G of ram as reported by @adampbeardsley .

**Comment by dannyjacobs** [comment]
I'm happy to close this issue, leaving open the issue of miriad taking up too much ram. #227
