### ISSUE TITLE
Fix test_phase_unphasePAPER in test_uvdata

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/pyuvdata#82]

**Comment by jpober** [comment]
Memory dump of my recollections looking into this:

The error is the zenith_ra's don't agree in the input miriad and output miriad after phasing and unphasing.  read_miriad gets zenith_ra from the lst time in the miriad file.  lst is written by the PAPER correlator, which uses aipy (which uses pyephem) to calculate lst from the JD timestamp.  Once the data is phased, zenith_ra is deleted and phase_center_ra is written.  Once the data is unphased, zenith_ra is re-written by pyuvdata which uses pyephem to calculate lst from the JD timestamp.  While the fact that both values are calculated from scratch both times makes it seem plausible they don't agree, but it's also somewhat surprising, since the lat/lon/alt agree in the input file and the pyuvdata known telescopes lists (I think) and both use pyephem to calculate lst.

**Comment by adampbeardsley** [comment]
Adding another data point that I think is related. We created a blank uvfits file using @aelanman's script (see issue #89). We then created two UVData objects, phased one to the first time in `time_array`, and phased the other to the first's `phase_center_ra`, `phase_center_dec`, `phase_center_epoch`. 
![image](https://cloud.githubusercontent.com/assets/4752917/20148949/3c95c018-a66c-11e6-90f7-8e0b47137f27.png)
The result is two objects that do not match - particularly the ra/dec do not agree. Note the test of equality also seems to be broken (see issue #93).

**Comment by adampbeardsley** [comment]
I'm spending a little time this morning trying to narrow down this problem. Here are some notes which may or may not be useful.

I recreated the `UV_raw` and `UV_phase` objects from the test in ipython to play with. First thing is to plot the difference in the `zenith_ra` arrays.
![image](https://cloud.githubusercontent.com/assets/4752917/20491799/c5024892-afcf-11e6-88e2-c7545b1f40d4.png)
I also tried created a `UV_phase2`, which is the same as `UV_phase`, but phased to ra,dec=(0.1,0.1), then unphased. The result is identical to `UV_phase`, suggesting the intermediate phase location is irrelevant.

Next I thought I'd try to recreate the calculation done by the PAPER correlator. @dannyjacobs suggests this is futile because lsts from the correlator are not to be trusted. Nevertheless, I'll document what I've done here. I used Zaki's PAPERCORR repo to look for where lst is calcuated. I found an example of the script `PAPERCORR/casper_correlator-1.2/tests/paper_test.py` calling `dacq.DataReceiver`, which does the calculation. I attempted to copy it, using the lat, lon, and jd from our `UV_raw` object, and interestingly I get the same answer as `UV_phase.zenith_ra`. I think this confirms that the lst is simply wrong in data file we're using, and our code could actually be right. 

I think the way to proceed is to replace the lst in our test file with an independently-calculated correct value. What do people think?

**Comment by adampbeardsley** [comment]
To summarize the last couple commits:
We moved on to a newer data file (from HERA), which did not exhibit the ramping behavior seen above. Instead there was a constant RA/DEC offset ~ 1e-6 rad. This turned out to be due to the RA/DEC in the file being calculated from the Lat/Lon in the file, which we were overwriting with known_telescopes. For the test, we added a new keyword to read_miriad which allows the user to keep the original antenna location, even if it does not match the values in known_telescopes. With this fix the test passes.
